// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "welcome": "Welcome to Calybook",

  "homeSearch_title": "Find and Book Venues",
  "homeSearch_description": "Select your location and category to find available venues"
};
export default messages;